### ISSUE TITLE
cvs connector for m2e 1.1.0?

### ISSUE THREAD

**Issue by cluick** [tesla/m2eclipse-cvs#4]
Hi folks,
after upgrading to Eclipse 4.2 and m2e 1.1.0 I'm missing the scm cvs connector at the m2e marketplace. 
Could you please tell me when a Juno-compatible build of cvs connector will be available? 
Thanks in advance,
Christof Luick.

**Comment by jvanzyl** [comment]
Here you go:

http://repository.tesla.io:8081/nexus/content/sites/m2e.extras/m2eclipse-cvs/0.13.0/N/0.13.0.201207081902/

**Comment by cluick** [comment]
Thanks! Now it works.
